alexcrichton/toml-rs

- Cargo.toml
- src/lib.rs
- src/parser.rs
- src/serialization.rs
- src/show.rs
- src/test/valid.rs
In other case using `toml-rs` causes build of old `rustc-serialize` which is not 
compatible with rust's master
> Updated serialize dependency

- src/decoder/serde.rs
Since `Value` implements `Serialize` already, it seems nice to have this, at least for symmetry. I don't think the same thing would be possible with rustc_serialize since its model requires knowing what to read. The implementation is basically a strait port of how Serde handles [deserialization](https://github.com/serde-rs/serde/blob/199ed417bd6afc2071d17759b8c7e0ab8d0ba4cc/serde_json/src/value.rs#L265-L347) for its own JSON type
> Implement Deserialize for Value

- src/lib.rs
Currently there is no way to lookup `self`. Because of `"".split('.').next() == Some("")`, the current functionality attempts to find children with key `""`.
This implements `Value::lookup` with empty string to return `self`.
> Implement Value::lookup for empty path to return self

- .travis.yml
Currently stable rust is not being built on Travis-CI.
> Add stable Rust build to Travis-CI config

- src/parser.rs
- tests/valid.rs
- tests/valid/example-bom.toml
If any valid UTF-8 encoded file should be possible to parse, then the parser must be able to handle a leading Byte Order Mark (BOM).
> Allow BOM (Byte order mark) in toml

- src/decoder/rustc_serialize.rs
Currently, floats never get removed from the `toml` field, even when they are parsed successfully. read_f64 was missing a call to toml.take()
> Remove floats from the Decoder.toml field when they get parsed

- src/lib.rs
Mutable access may sometimes be desired in order to change values
in the toml table. This can be used for dynamic configurations which
will be easy to modify and store.
lookup_mut requires a recursive method due to the borrow checker
not allowing to have more than one mutable reference in the same
scope.
> Add lookup_mut method for mutable access

- src/lib.rs
- src/parser.rs
These commits allow one to search for tables with unconventional names. Example:
```rust
let table: toml::Value = r#"[table."name.other"] value = 0"#.parse().unwrap();
let look = table.lookup(r#"table."name.other".value"#).unwrap();
```
These commits have some breaking changes for the tests, as sending a raw " into lookup will no longer work correctly. One must send `r#""\"""#` or `"\"\\\"\""` instead.
Performance: It may be possible to have a slight performance decrease for all lookups because each entry is now parsed and put into a String. This can be remedied by creating a lookup_simple method that takes simple names only.
Bugs discovered: the parser fails to parse "" and '' as a key name.
> Allow advanced lookups in lookup and lookup_mut

- src/parser.rs
- tests/valid/unicode-escape.json
- tests/valid/unicode-escape.toml
Current parser generates error below if a string contains unicode escape code followed by some unicode character, `"\u03B4α"` for example.
```
expected 4 hex digits after a `u` escape
```
This is an attempt to fix it.
> Fix wrong handling of unicode escape code

- src/lib.rs
- src/parser.rs
- tests/invalid.rs
- tests/invalid/key-after-array.toml
- tests/invalid/key-after-table.toml
Currently this library accepts this TOML as valid:
```
[table] key = "value"
```
I'm pretty sure this is not valid TOML. The [spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#table) says:
> They appear in square brackets on a line by themselves
And pytoml rejects the sample TOML above as invalid.
This pull request changes the library to reject TOML that is malformed in this way.
I am not particularly attached to this particular solution, but I'd rather present a PR than a bug report, so I gave it my best, incredibly clumsy, shot. In particular I'm pretty sure the line numbers I put into the ParserError are not right.
An important note:
Because this was previously accepted as valid, this will be a **breaking change for Cargo**. In particular, several versions …
> Require newline after table

- src/parser.rs
Due to requiring an empty line after a table name, the follow valid (I think, having checked against the grammar) input is now rejected, where it was not before:
```
[table]
```
NB that it is still accepted if followed by a blank line:
```
[table]
```
The Cargo.toml files for the crates "decibel" and "water" don't parse without a fix for this.
> Accept empty table

- src/lib.rs
Rationale:
- The path has nothing to do with the result.
- The path has no need to live as long as the Value/self.
- In some cases it can be hard to actually build a path that meets
the same lifetime requirements as the Value or String slice result.
I submit to you that lifetime elision will not work with my use cases.
I really need the 'path' lifetime to be completely disassociated from the Value or String slice result.
I tried to provide an example in my original Issue. If my example was confusing or poorly worded please ask me to clean it up and I will happily do so.
Thank you.
> lookup() and lookup_mut() lifetime enhancements.

- src/decoder/mod.rs
- src/decoder/rustc_serialize.rs
- src/encoder/mod.rs
- src/encoder/rustc_serialize.rs
- src/lib.rs
- src/parser.rs
Fix a bunch of lints indicated by clippy, most common one was useless `format!`. Most notable change is to implement `Default` for `State` and derive it for `Encoder`. Also closes #102.
> Clippy run and implement Default for State and Enconder

- src/display.rs
- tests/formatting.rs
Code I used to verify:
```rust
extern crate rustc_serialize;
extern crate toml;
use toml::encode_str;
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct User {
pub name: String,
pub surname: String,
}
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct Users {
pub user: Vec<User>,
}
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct UsersWithString {
pub string: String,
pub user: Vec<User>,
}
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct AUserx2 {
pub user0: User,
pub user1: User,
}
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct AUserWithString {
pub string: String,
pub user: User,
}
fn main() {
println!("\"{}\"", …
```
> Don't space out the first table or array if not needed

- README.md
I end up on GitHub wondering what the latest version is and having to go find it on crates.io a lot.
> Add a latest version shield to the readme

- src/value.rs
- tests/display.rs
Fixes writing array after normal values when writing table, that caused this diff after deserialization and serialization to `toml::Value`.
```diff
[package]
-authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libpango-1.0"
homepage = "http://gtk-rs.org/"
-keywords = ["pango", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "pango"
name = "pango-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.3.2"
+authors = ["The Gtk-rs Project Developers"]
+keywords = ["pango", "ffi", "gtk-rs", "gnome"]
```
> Fixed sorting of table values

- src/datetime.rs
- src/de.rs
- src/ser.rs
- src/tokens.rs
- tests/valid.rs
This also fixes quite a lot of #139.
Let me know if anything isn't preferred style.
> Fix issues indicated by clippy

- src/de.rs
- src/ser.rs
- src/value.rs
- tests/serde.rs
Close #164
It currently doesn't work for deserialization and I have no idea where it fails.
```
thread 'parse_enum_string' panicked at 'toml.clone().try_into() failed with invalid type: string "desc", expected enum Sort for key `a`', tests/serde.rs:344
```
Some of the changes are probably not needed/not optimal, I was following the serde docs and serde-json repo trying to make it work first.
> Allow to deserialize/serialize into enums

- src/de.rs
I'm trying to improve the error reporting in clippy. Since we forward to rustc's error reporting, adding a line + col info to the error would allow rustc to actually hilight the error through the regular mechanisms instead of us producing a "help: some error at file:line" through the `Display` impl of `Error`
> Allow extracting the location of the error

- src/ser.rs
One more step in order to fix #171: add an example for toml::ser::to_string
Once again the TOML example I wrote is inspired by the first example of the TOML readme: https://github.com/toml-lang/toml#example (this time it's about database configuration).
> add example for to_string

- src/de.rs
First step in order to fix https://github.com/alexcrichton/toml-rs/issues/171: add an example for `toml::de::from_str`
The TOML string used in this example is inspired by the example given on the official TOML repo: https://github.com/toml-lang/toml and code itself is inspired by the example from the index page of this crate: https://docs.rs/toml/0.4.0/toml/index.html#deserialization-and-serialization. I tried to make it a bit shorter and a bit different (in comparison with the index page), maybe I should have only copy/pasted [it](https://docs.rs/toml/0.4.0/toml/index.html#deserialization-and-serialization) (but I think user would prefer different examples across pages). 
The "name" in TOML is an arbitrary choice (not really, in fact it's the name of my daughter, since the original TOML …
> add example for from_str

- src/de.rs
- src/ser.rs
- tests/invalid-encoder-misc.rs
- tests/invalid-misc.rs
This improves handling of invalid numbers (e.g. `float` or `inf`) by:
- Return an error when deserializing huge numbers like `9e99999` instead of silently deserializing them into `inf`
- Return an error serializing a non-finite number (`nan`, `+inf`, or `-inf`).
Unfortunately, I also ended up adding a variant to the public `toml::se::Error` enum, so this is a breaking change and would need a version bump.
Addresses https://github.com/alexcrichton/toml-rs/issues/181
> Better invalid number handling

- src/ser.rs
- tests/serde.rs
- tests/valid.rs
- tests/valid/table-array-nest-no-keys.json
- tests/valid/table-array-nest-no-keys.toml
When serializing nested table like `[a.b.c]`, `toml` will leave out the super-tables if it can. Unfortunately, if one of the super-tables is actually an array of tables (`[[ a ]]`), then leaving out the super-table changes the value being encoded. For example:
```toml
[[ a ]]
[[ a.b ]]
```
which is equivalent to `{"a": [{"b": [{}]}]}` is currently serialized into
```toml
[[ a.b ]]
```
which is equivalent to `{"a": {"b": [{}]}}`, which is not the same.
To fix this, whenever we emit a table header, we check for  `[[ a ]]` parents and emit table headers for them first if necessary.
Closes #180
> Serialize nested array of tables correctly

- src/value.rs
I'm currently in a situation where I have to deserialize a `BTreeMap<String, ::toml::value::Value>` into a `BTreeMap<String, V>` where `V: Deserialize<'de>`.
Currently, the only way I found to do this is as such:
```rust
use serde::de::{self, Deserialize};
let from_map: BTreeMap<String, ::toml::value::Value> = ...;
let to_map: BTreeMap<String, V> =
Deserialize::deserialize(
de::value::MapAccessDeserializer::new(
de::value::MapDeserializer::new(from_map.into_iter())))?;
```
but this requires `Value` to implement `IntoDeserializer`. While there might be an easier/different way to accomplish this deserialization (cc @dtolnay), I guess implementing `IntoDeserializer` doesn't hurt and works for the above example.
> Implement `IntoDeserializer` for `Value`

- src/lib.rs
Because of the docs, I used `0.2.1` instead of `0.4.2` in my project.
https://docs.rs/toml/0.4.2/toml/
> updated toml version in the docs to 0.4.2

- src/lib.rs
- src/ser.rs
- tests/pretty.rs
This is an MVP of the "pretty" configuration impelmentation. There are some things I would still like to do (like avoid having to clone `Settings`) and there are still a bunch of tests that need to be added but this seems to work 🎉 🎉 
This is necessary for:
- vitiral/artifact#87
- vitiral/artifact#152
I would particularily like feedback from @alexcrichton on:
- Is it okay to have a `Settings` struct instead of a `Formatter` trait, as suggested by @dtolnay. @dtolnay what do you think about this? I see the trait as probably "higher speed" but I don't think that's as much a requirement for toml as it is for json.
- What should the name be? Is `toml::ser::Settings` good?
Improvements needed:
- The `Serializer::pretty` is [mimicking serde_json's][1] implementation, but we should make `pretty` …
> close #119: allow "pretty" configuration

- src/ser.rs
- tests/pretty.rs
- tests/valid.rs
This is to demonstrate the tripple quote problem I theorized: that if there are `'''` in a pretty string there will be issues. However, the issue I hit was not as expected.
The written test prints the following:
```
EXPECTED:                                              
[example]                                            
text = '''                                          
this is the first line                                                                                   
This has a ''\' in it for no reason                                                                      
this is the third line                               
'''                                                 
RESULT: …
```
> demonstrate tripple quote problem

- src/ser.rs
- tests/pretty.rs
@killercup noticed in killercup/cargo-edit#163
> This format is pretty (😄), except for the missing newlines around these sections
"these sections" being array items. I actually think that this was probably broken before my changes (but maybe not). Never-the-less this PR fixes the issue and adds spaces around array-table items.
Before:
```
[[array]]
key = "foo"
[[array]]
key = "bar"
[table]
key = "baz"
```
After:
```
[[array]]
key = "foo"
[[array]]
key = "bar"
[table]
key = "baz"
```
> add spaces between array items and test for them

- src/ser.rs
- tests/pretty.rs
We should be able to disable literal `'` and `'''` strings and just use `"` or `"""` depending on whether there are newlines.
In the process I found a bug with the deserialization module that I added a FIXME for.
@killercup requested this in killercup/cargo-edit#163
> add pretty_string_literal to be able to disable literal strings

- src/de.rs
- src/tokens.rs
This is the first step at addressing #236.
This modifies the tokenizer to emit span information for each token as well, and does the necessary modifications to deserialization to keep things working for now.
> Make Tokenizer emit spans

- Cargo.toml
- src/datetime.rs
- src/de.rs
- src/lib.rs
- src/ser.rs
- src/spanned.rs
- src/tokens.rs
- src/value.rs
- test-suite/tests/spanned.rs
This PR introduces Spanned based on the previous POC by @dtolnay.
Internally we deserialize spans as "intermediate structs" with special naming conventions, which communicates to the `Deserializer` that it should emit a Map with similarly special names that we can pick up.
This PR contains a couple of changes:
* Introduces a `Spanned<T>` type that can be used in structs to encapsulate spans.
* Unified the naming convention of constants for `datetime` and `spanned`.
* Added `eat_spanned` and `expect_spanned` to `Tokenizer` to correctly parse tables and arrays. 
I'm unsure it is complete, the infrastructure needed to support Datetime permeates more of the deserialize infrastructure, but I haven't been able to decipher _why_ yet. Any feedback is appreciated.
Ironically this doesn't help me …
> Support spans when deserializing serde structures

- src/ser.rs
- test-suite/tests/valid.rs
- test-suite/tests/valid/quote-surrounded-value.json
- test-suite/tests/valid/quote-surrounded-value.toml
Fixes #262.
The `can_be_pretty && found_singles > 0` check is not required for correctness and may be an unwarranted attempt at optimization, let me know if you'd rather get rid of it.
As a side note I also found the `can_be_pretty` variable name here confusing. It seems like e.g. `can_be_literal` would be more accurate. After all, it only controls whether `Repr::Std` or `Repr::Literal` is used.
> Avoid panic on pretty string ending in single quote

- src/value.rs
- test-suite/tests/serde.rs
With https://github.com/alexcrichton/toml-rs/pull/245 already allowing tuples, tuple structs and tuple variants for string serialization, there is no reason `toml::Value` should not have the same capability as well!
> Support tuple Serde types for `Value`

- examples/enum_external.rs
- src/de.rs
- tests/enum_external_deserialize.rs
cc: #225, #222
~~The tuple variant hasn't been implemented yet, I'm having trouble figuring it out.~~
See #225 for ongoing discussion -- what should / should not be supported.
Short, the following TOML:
```toml
plain = "Plain"
plain_table = { Plain = {} }
tuple = { Tuple = { 0 = 123, 1 = true } }
struct = { Struct = { value = 123 } }
newtype = { NewType = "value" }
my_enum = [
{ Plain = {} },
{ Tuple = { 0 = 123, 1 = true } },
{ NewType = "value" },
{ Struct = { value = 123 } }
]
```
with the following types:
```rust
#[derive(Debug, Deserialize)]
struct Config {
plain: MyEnum,
plain_table: MyEnum,
tuple: MyEnum,
#[serde(rename = "struct")]
structv: MyEnum,
newtype: MyEnum,
my_enum: Vec<MyEnum>,
}
#[derive(Debug, Deserialize)]
enum MyEnum {
Plain,
Tuple(i64, bool),
NewType(String),
Struct …
```
> Issue 255: Externally tagged enum deserialization

- Cargo.toml
- src/de.rs
- test-suite/tests/backcompat.rs
- test-suite/tests/invalid.rs
- test-suite/tests/invalid/duplicate-table.toml
This commit fixes #279 where a case of duplicate table headers slipped
through the cracks. This also adds an option to disable this new
validation to allow Cargo to preserve backwards compatibility.
> Fix disallowing duplicate table headers

- src/de.rs
Add PartialEq trait to Error, ErrorInner and ErrorKind.
Relevant issue: https://github.com/alexcrichton/toml-rs/issues/291
All Tests pass.
> Add PartialEq to Toml::de

- src/tokens.rs
The previous implementation of `read_string`, when looking for
delimiters ending the multi-line string and failing to find exactly
three in succession, always put a single delimiter back. This is
incorrect when exactly two delimiters are present.
Put back the correct number of delimiters depending on how many have
been already consumed from input.
The issue could be triggered only with `Owned` representation of
`MaybeString`, since otherwise `push` operation is no-op.
> Fix parsing of repeated delimiters inside multi-line strings

- test-suite/Cargo.toml
- test-suite/build.rs
- test-suite/tests/float.rs
- test-suite/tests/macros.rs
This is no longer necessary, as <1.20 is no longer supported.
> Remove rustc version checking.

- Cargo.toml
toml-rs depends on some Serde types not present in Serde 1.0.0 (e.g
BorrowedStrDeserializer). By explicitly depending on a newever version,
we ensure compatibility with any crates using '-Z minimal-versions'
Note that we could probably depend on an older version of Serde, but I
didn't see much point in finding the exact minimum patch release that's
compatible with toml-rs
> Bump Serde dependency to 1.0.97

- src/de.rs
- test-suite/tests/backcompat.rs
- test-suite/tests/datetime.rs
- test-suite/tests/invalid-misc.rs
- test-suite/tests/invalid.rs
- test-suite/tests/parser.rs
- test-suite/tests/serde.rs
Error messages now show "column N" when the line number is available.
Not only does this make the messages more useful, but it's inline with how
`serde_json` displays them: https://github.com/serde-rs/json/blob/e3a2c3af66f4/src/error.rs#L368
Subsequent commits will add `line` and `col` to additional error kinds.
> Show "column" in Error messages

- test-suite/tests/backcompat.rs
- test-suite/tests/datetime.rs
- test-suite/tests/invalid-misc.rs
- test-suite/tests/invalid.rs
- test-suite/tests/parser.rs
- test-suite/tests/serde.rs
Currently, token errors show their line number, but not their column number.
And parsing errors, include neither (the `Error` itself doesn't even have
the information).
In subsequent commits, token error messages will include their column number
in the message, and parsing errors will include their line and column number.
This commit expands all error messages in the tests to their full text, for
easier verification of that change.
This change adopts the usage of the `bad` macro pattern that was found in
some of the tests, across all of the tests.
> Fully expand error messages in tests

- src/lib.rs
- src/spanned.rs
The `Spanned` struct was originally included in the docs as a re-export, but rustdoc doesn't render re-exports if the module from which it's exported isn't documented.
Since `Spanned` is the only public item inside the `spanned` module this commit shows the struct as a normal item in the index, and moves the example from the module docs to the struct docs.
Fixes https://github.com/alexcrichton/toml-rs/issues/309
> Include Spanned in the docs

- src/de.rs
- src/ser.rs
As part of rust-lang/rust#61172, this warning appears in 1.37 (beta).
> Squelch explicit_outlives_requirements warning.

- src/de.rs
- test-suite/Cargo.toml
- test-suite/tests/datetime.rs
- test-suite/tests/de-errors.rs
- test-suite/tests/invalid-misc.rs
- test-suite/tests/invalid.rs
- test-suite/tests/parser.rs
- test-suite/tests/serde.rs
This change adds offset information to Errors as they bubble up the visitor
chain, and before exiting, adds line and column information based on that
offset. The effect is that _most_ Errors now have correct location information,
and in other cases, it's close (but not quite as exact as it should be).
The new test (`de-errors.rs`), serves to show the positioning of custom
deserializer Errors. These are the most problematic ones, because table-level
errors, require guessing the position from the elements. Unfortunately,
this isn't great, but it's better than nothing. The tests highlight where
the positioning falls short.
This is the continuation of #312 and #313.
> Add line and column to all Errors

- src/de.rs
Hi there! 
Use case is to allow something like this:
```
pub fn load(file_path: &str) -> Result<TaskToml, std::io::Error> {
let t: TaskToml = toml::from_str(
&fs::read_to_string(file_path)?
)?;
Ok(t)
}
```
> Allow conversion from de::Error to std::io::error

- src/de.rs
- src/value.rs
Removed matches that were used to compare Enum variants for equality in
favor of using `discriminant` from [1.21.0](https://doc.rust-lang.org/std/mem/fn.discriminant.html)
that's cleaner and more idiomatic.
> Simplified Logic when comparing discriminants

- src/de.rs
- test-suite/tests/de-errors.rs
The new exposure to line/col in errors uncovered an issue with how `to_linecol` was computing the line/col with a CRLF document. It was not including the CR characters in the offset computation, causing the result to skew for each line.
> Fix error line/column when using CRLF line endings.

- src/datetime.rs
- src/de.rs
- src/map.rs
- src/ser.rs
- src/spanned.rs
- src/tokens.rs
- src/value.rs
Hi,
Trying to resolve issue #139 and hit a roadblock when it comes to how to handle certain situations. A majority of the warnings and errors have been resolved. I have 1 remaining warning and a question revolving around the use of `drop` in `src/ser.rs`.
Firstly, the one remaining warning
```
warning: methods called `to_*` usually take self by reference; consider choosing a less ambiguous name
--> src/tokens.rs:505:17
|
505 |     fn to_owned(&mut self, input: &str) {
|                 ^^^^^^^^^
|
= note: `#[warn(clippy::wrong_self_convention)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
```
Personally, I think that the name of the method properly describes the purpose. Just to entertain it what would …
> Fix clippy warnings and errors

- src/de.rs
- test-suite/tests/parser.rs
- test-suite/tests/valid.rs
- test-suite/tests/valid/float-exponent.json
- test-suite/tests/valid/float-exponent.toml
Zero-prefixed exponents were added in https://github.com/toml-lang/toml/pull/656.
> Allow zero-prefixed float exponents.

- src/de.rs
Not sure why this wasn't implemented before, since `ser::Error` has implemented `PartialEq` and `Eq` as of PR #144.
> Make `de::Error` `Eq` in addition to current `PartialEq`

- src/de.rs
- src/ser.rs
- src/spanned.rs
There were some `#[doc(hidden)]` attributes that weren't necessary. Other uses were replaced by `pub(crate)`.
> Remove redundant #[doc(hidden)] attributes

- src/spanned.rs
See https://github.com/alexcrichton/toml-rs/issues/236#issuecomment-537994005
> `Spanned::get_mut` should return a mutable reference

- Cargo.toml
since this repository is no longer using Travis CI for development.
> Remove outdated Travis CI badge

- src/spanned.rs
- test-suite/tests/spanned-impls.rs
This is because we want to be able to index into HashMap<Spanned<String>, T>
with a dummy span and get results where only the content has to match.
For more info, see #327 and #341
>  Spanned: impl PartialEq, Eq, Hash, PartialOrd, Ord in terms of the value

- src/de.rs
- test-suite/tests/spanned.rs
This provides "support" for dotted table spans by setting them to 0. While special cases could get special case logic, in the general case toml allows for dotted tables without well defined spans.
In this document, the span for the `dependencies` table is for example not well-defined:
```toml
[dependencies.serde]
optional = true
[package]
name = "toml-spanned-value"
[dependencies]
toml = "0.7"
```
The package table for example does have a well-defined span and thus could be special-cased.
> Support for dotted table spans

- src/de.rs
- test-suite/tests/linear.rs
Fixes #342.
In particular, see my comment https://github.com/alexcrichton/toml-rs/issues/342#issuecomment-546190394
Values that I recorded on my machine for running the code `measure_time(n, |i| format!("[header_no_{}]\n", i))` function for varying `n`:
| benchmark  | optimizations | before this PR | after this PR |
|------------|---------------|----------------|---------------|
|          1k|             no|           170ms|           48ms|
|         10k|             no|         14 191ms|          483ms|
|        100k|             no|             n/a|         5 077ms|
|          1k|            yes|             5ms|            4ms|
|         10k|            yes|           311ms|           39ms|
|        100k|            yes|         63 850ms|          364ms|
You can nicely see how before …
> Decrease deserialization complexity from quadratic to linear

- src/de.rs
Replaced copied with filter_map for rustc 1.35 compatibility. This should fix projects like mentioned by @dvogt23 in issue #353 which are still using rustc 1.35 might automatically pull 0.5.4 since it is patch semver.
```
% cargo +1.35.0 test
Compiling toml v0.5.4 (/Users/max/src/opensource/toml-rs)
Finished dev [unoptimized + debuginfo] target(s) in 4.37s
Running target/debug/deps/toml-bd94711eee332035
running 6 tests
test tokens::tests::bad_comment ... ok
test tokens::tests::bare_cr_bad ... ok
test tokens::tests::all ... ok
test tokens::tests::keylike ... ok
test tokens::tests::basic_strings ... ok
test tokens::tests::literal_strings ... ok
test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/enum_external_deserialize-e6d4b6530bf5385b …
```
> iter_copied rustc 1.35 compatibility fix #353

- src/datetime.rs
- src/de.rs
- src/ser.rs
`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes all implementations of `description` in all error types
Related PR: https://github.com/rust-lang/rust/pull/66919
> Remove deprecated Error::description

- src/ser.rs
Before this change, there were a couple cases in `DateStrEmitter` report `KeyNotString` errors instead of `DateInvalid`.
> Fix a couple errors in DateStrEmitter

- src/lib.rs
- src/value.rs
Thanks for your efforts making this awesome library! 🙌
Here's a suggestion.
> Rustdoc: Add links. Show all reexports as reexports.

- src/tokens.rs
- test-suite/tests/valid.rs
- test-suite/tests/valid/string-delim-end.json
- test-suite/tests/valid/string-delim-end.toml
TOML allows (unlike many other formats) up to 2
additonal quotes that are part of the string:
```
basic = """2 extra quotes -->"""""
literal = '''here too ''''
```
Changed in TOML v1.0.0-rc.1
See also #392
> Allow delimiter quotes at the end of multiline strings

- src/lib.rs
- src/value.rs
Removes `#[doc(no_inline)]` from the `Spanned` re-export in `lib.rs` and from the `Datetime*` re-exports in `value.rs`
Resolves #408
> Show `Spanned` and `Datetime` in docs

- src/datetime.rs
Found this typo while reading through the source: "thiese" -> "these"
> Fix comment typo

- src/ser.rs
https://github.com/rust-lang/rust/pull/78618 changed the display behavior of `-0.0` to include the `-` symbol which caused the serialization code to emit `--0.0`.
> Fix serialization of -0.0.

- src/value.rs
Was reading the source and this jumped out at me.
It's not much but deserialising toml faster seems like a good thing.
> Use entry api to remove a lookup in deserialisation loop

- src/datetime.rs
- src/value.rs
In issue #431, @samuelcolvin wrote:
> I'd like to be able to access the fields of Datetime (and then obviously Date and Time) directly rather than having to re-parse the result of to_string().
>
> I don't need chrono integration, just direct access to the integer values.
>
> Would you accept a PR for this?
Then @alexcrichton replied:
> Seems reasonable to me to add!
> Make datetime.rs structs and fields public #431

- examples/decode.rs
- examples/enum_external.rs
The examples deny warnings, however a couple of examples deserialise TOML into
structs. The fields of these structs are never read, which breaks cargo test
in nightly mode.
Allow dead code to fix the CI build, as discussed on #447.
> Allow dead code in examples to fix CI build
