src/lib.rs, src/parser.rs, src/serialization.rs, src/show.rs, src/test/valid.rs
- features
- macro reform
- String/Show split in formatter
=> Update to master

src/parser.rs, tests/invalid.rs
Please review this pull request!
=> Fix Parser::to_linecol

serde-tests/Cargo.toml, serde-tests/build.rs, src/encoder/mod.rs, src/encoder/serde.rs
just leaving this here for future reference so noone needs to repeat any work
=> WIP: adjust for seq/map ser revamp

Cargo.toml, serde-tests/Cargo.lock, serde-tests/Cargo.toml, serde-tests/build.rs, src/decoder/mod.rs, src/decoder/serde.rs, src/encoder/mod.rs, src/encoder/serde.rs
Supersedes #104. I kept those two commits unmodified.
=> Update to serde 0.8.0

src/value.rs
=> Add exhaustive From<T> impls for Value

src/ser.rs
definitely not an emergency, I just felt like it needed to be done eventually.
Also fixed a couple of docs that I missed.
=> reference count settings to bump performance a bit

tests/pretty.rs
I must have been mistaken before, it works fine (weird...)
=> close #209: remove FIXME, appears to have been invalid

src/value.rs
One sentence was wrong, and some other ones missing a full-stop.
=> [value] Fix some method docs

README.md
Copied my license text from you and realized it was referencing Serde. Don't mess with Big License!
=> Small copy-paste error in license text

src/tokens.rs, test-suite/tests/valid/unicode-escape.json, test-suite/tests/valid/unicode-escape.toml
Fixes #240.
This is my first try at writing some Rust, so bear with me. I am still struggling with writing a test case...
=> Treat unicode hex digits case-insensitively

src/tokens.rs, test-suite/tests/invalid-misc.rs
=> 0.5: Reject 0x7f (DEL) in strings.

src/datetime.rs, src/de.rs, test-suite/tests/datetime.rs
=> 0.5: Support space separator in datetime.

src/de.rs, test-suite/tests/invalid-misc.rs, test-suite/tests/valid.rs, test-suite/tests/valid/dotted-keys.json, test-suite/tests/valid/dotted-keys.toml
=> 0.5: Support dotted keys.

src/macros.rs, test-suite/tests/macros.rs
- Space in datetime.
- +- inf, nan, 0.0
- Dotted keys.
=> Support the new 0.5 syntax in the toml! macro.

src/value.rs, test-suite/tests/serde.rs
Fixes https://github.com/serde-rs/json/issues/471
=> Support deserializing from other integer types

src/de.rs, src/tokens.rs, test-suite/tests/parser.rs
=> Fix multi-line strings are not allowed for key (#260)

src/tokens.rs, test-suite/tests/invalid/string-bad-line-ending-escape.toml, test-suite/tests/valid/multiline-string.json, test-suite/tests/valid/multiline-string.toml
=> Allow whitespace after line ending backslash (#162)

src/ser.rs
=> Allow newtype key

src/spanned.rs
Should any other traits be derived?
=> Derive Clone+PartialEq for Spanned

src/de.rs, test-suite/tests/spanned.rs
Filing as a separate PR because it adds a feature to the already present support to deserialize spanned structures. Related to #327
=> Suppport deserialization of Spanned<> at the top level

src/de.rs, tests/enum_external_deserialize.rs
Add support for deserializing enums from nested dotted tables.
=> Nested dotted-table enums

src/de.rs, src/spanned.rs, test-suite/tests/spanned.rs
This adds support for deserialization of table key span information. cc #327
=> Support deserializing spanned keys

src/de.rs, test-suite/tests/datetime.rs, test-suite/tests/invalid.rs, test-suite/tests/parser.rs
=> Improve error message when parsing unquoted string
